export enum Layer {
  BUILT_AREA = 'builtArea',
  ENVIRONMENTAL_LICENSING = 'environmentalLicensing',
  NON_BUILT_AREA = 'nonBuiltArea',
  SOIL_USAGE = 'soilUsage',
  TREE = 'tree',
  URBAN_LICENSING = 'urbanLicensing',
  POPULATION2010 = 'population2010',
  PERCENTAGEHOUSEHOLDSTREES = 'PercentageHouseholdsTrees',
  PERCENTAGEHOUSEHOLDSWHEELCHAIRRAMPSURROUNDINGS2010 = 'PercentageHouseholdsWheelchairRampSurroundings2010',
  PERCENTAGEPOPULATIONPIPED2010 = 'PercentagePopulationPiped2010',
  PERCENTAGEPOPULATIONGARBAGECOLLECTION2010 = 'PercentagePopulationGarbageCollection2010',
  PERCENTAGEPOPULATIONSANITARYSEWAGE2010 = 'PercentagePopulationSanitarySewage2010',
  AVERAGEINCOME2010 = 'AverageIncome2010',
  NUMBERHOUSEHOLDS2010 = 'NumberHouseholds2010',
  DEMOGRAPHICDENSITY2010 = 'DemographicDensity2010',
  POPULATIONGROWTH20002010 = 'PopulationGrowth20002010',
  METROSTATION = 'MetroStation',
  BLUESTRIP = 'BlueStrip',
  METROLINE = 'MetroLine',
  TOTALRECIFELINE = 'TotalRecifeLine',
  CYCLELANEMESH2022 = 'CycleLaneMesh2022',
  PEDESTRIANMOBILITYTACTICALURBANISM = 'PedestrianMobilityTacticalUrbanism',
  ZONING = 'Zoning'
}
