name: deploy-dev

on:
  workflow_run:
    workflows: ["testing-push"]
    branches: [main]
    types: [completed]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_DEV_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}